/**
 * Report Generator
 *
 * Generates markdown reports from test results.
 */

import * as fs from "fs"
import * as path from "path"
import type { TestReport, SuiteResult, TestResult, TestError } from "../types"
import { TEST_CONFIG } from "../config"

/**
 * Generate a timestamp string for filenames
 */
function getTimestamp(): string {
  const now = new Date()
  return now.toISOString().replace(/[:.]/g, "-").slice(0, 19)
}

/**
 * Format duration in human readable form
 */
function formatDuration(ms: number): string {
  if (ms < 1000) return `${ms}ms`
  if (ms < 60000) return `${(ms / 1000).toFixed(1)}s`
  const minutes = Math.floor(ms / 60000)
  const seconds = Math.floor((ms % 60000) / 1000)
  return `${minutes}m ${seconds}s`
}

/**
 * Get status emoji
 */
function statusEmoji(status: string): string {
  switch (status) {
    case "passed": return "[PASS]"
    case "failed": return "[FAIL]"
    case "skipped": return "[SKIP]"
    default: return "[????]"
  }
}

/**
 * Generate markdown report content
 */
export function generateReportContent(report: TestReport): string {
  const lines: string[] = []

  // Header
  lines.push("# E2E Test Report - ReNew Platform")
  lines.push("")
  lines.push(`**Date:** ${report.timestamp}`)
  lines.push(`**Environment:** ${report.environment}`)
  lines.push(`**Duration:** ${formatDuration(report.duration)}`)
  lines.push("")

  // Summary table
  lines.push("## Summary")
  lines.push("")
  lines.push("| Metric | Value |")
  lines.push("|--------|-------|")
  lines.push(`| Total Tests | ${report.summary.total} |`)
  lines.push(`| Passed | ${report.summary.passed} |`)
  lines.push(`| Failed | ${report.summary.failed} |`)
  lines.push(`| Skipped | ${report.summary.skipped} |`)
  lines.push(`| Pass Rate | ${report.summary.passRate.toFixed(1)}% |`)
  lines.push("")

  // Quick status indicator
  if (report.summary.failed === 0) {
    lines.push("> **All tests passed!**")
  } else {
    lines.push(`> **${report.summary.failed} test(s) failed** - see details below`)
  }
  lines.push("")

  // Results by suite
  lines.push("## Results by Suite")
  lines.push("")

  for (const suite of report.suites) {
    const suiteStatus = suite.failed === 0 ? "passed" : "failed"
    lines.push(`### ${suite.name} (${suite.passed}/${suite.results.length} passed)`)
    lines.push("")

    for (const test of suite.results) {
      const emoji = statusEmoji(test.status)
      lines.push(`- ${emoji} ${test.name}`)

      if (test.status === "failed" && test.error) {
        lines.push(`  - **Error:** ${test.error.message}`)
        if (test.screenshot) {
          lines.push(`  - **Screenshot:** ${test.screenshot}`)
        }
      }
    }
    lines.push("")
  }

  // Failed tests details (if any)
  if (report.summary.failed > 0) {
    lines.push("## Failed Tests Details")
    lines.push("")

    for (const suite of report.suites) {
      const failedTests = suite.results.filter(t => t.status === "failed")
      if (failedTests.length === 0) continue

      for (const test of failedTests) {
        lines.push(`### ${suite.name} > ${test.name}`)
        lines.push("")
        if (test.error) {
          lines.push(`**Error Type:** ${test.error.type}`)
          lines.push("")
          lines.push(`**Message:** ${test.error.message}`)
          lines.push("")
          if (test.error.stack) {
            lines.push("**Stack Trace:**")
            lines.push("```")
            lines.push(test.error.stack.slice(0, 500))
            lines.push("```")
            lines.push("")
          }
        }
        if (test.screenshot) {
          lines.push(`**Screenshot:** [View](./screenshots/${test.screenshot})`)
          lines.push("")
        }
        lines.push(`**Duration:** ${formatDuration(test.duration)}`)
        lines.push("")
        lines.push("---")
        lines.push("")
      }
    }
  }

  // Screenshots list
  if (report.screenshots.length > 0) {
    lines.push("## Screenshots")
    lines.push("")
    for (const screenshot of report.screenshots) {
      lines.push(`- [${screenshot}](./screenshots/${screenshot})`)
    }
    lines.push("")
  }

  // Footer
  lines.push("---")
  lines.push("")
  lines.push("*Generated by ReNew Platform E2E Test Suite*")

  return lines.join("\n")
}

/**
 * Save report to file
 */
export function saveReport(report: TestReport): string {
  const timestamp = getTimestamp()
  const filename = `test-run-${timestamp}.md`
  const reportsDir = path.join(process.cwd(), "scripts", "e2e-tests", "reports")

  // Ensure reports directory exists
  if (!fs.existsSync(reportsDir)) {
    fs.mkdirSync(reportsDir, { recursive: true })
  }

  const filepath = path.join(reportsDir, filename)
  const content = generateReportContent(report)

  fs.writeFileSync(filepath, content, "utf-8")
  console.log(`[Report] Saved to: ${filepath}`)

  return filepath
}

/**
 * Create a TestReport from suite results
 */
export function createReport(
  suites: SuiteResult[],
  startTime: number,
  screenshots: string[] = []
): TestReport {
  const endTime = Date.now()
  const duration = endTime - startTime

  // Calculate totals
  let total = 0
  let passed = 0
  let failed = 0
  let skipped = 0
  const errors: TestError[] = []

  for (const suite of suites) {
    total += suite.results.length
    passed += suite.passed
    failed += suite.failed
    skipped += suite.skipped

    for (const test of suite.results) {
      if (test.error) {
        errors.push(test.error)
      }
    }
  }

  const passRate = total > 0 ? (passed / total) * 100 : 0

  return {
    timestamp: new Date().toISOString(),
    environment: TEST_CONFIG.baseUrl,
    duration,
    summary: {
      total,
      passed,
      failed,
      skipped,
      passRate,
    },
    suites,
    screenshots,
    errors,
  }
}

/**
 * Print summary to console
 */
export function printSummary(report: TestReport): void {
  console.log("")
  console.log("=".repeat(60))
  console.log("E2E TEST SUMMARY")
  console.log("=".repeat(60))
  console.log("")
  console.log(`Environment: ${report.environment}`)
  console.log(`Duration:    ${formatDuration(report.duration)}`)
  console.log("")
  console.log(`Total:   ${report.summary.total}`)
  console.log(`Passed:  ${report.summary.passed}`)
  console.log(`Failed:  ${report.summary.failed}`)
  console.log(`Skipped: ${report.summary.skipped}`)
  console.log(`Pass Rate: ${report.summary.passRate.toFixed(1)}%`)
  console.log("")

  if (report.summary.failed > 0) {
    console.log("FAILED TESTS:")
    for (const suite of report.suites) {
      for (const test of suite.results) {
        if (test.status === "failed") {
          console.log(`  - ${suite.name} > ${test.name}`)
          if (test.error) {
            console.log(`    ${test.error.message}`)
          }
        }
      }
    }
    console.log("")
  }

  console.log("=".repeat(60))

  if (report.summary.failed === 0) {
    console.log("ALL TESTS PASSED!")
  } else {
    console.log(`${report.summary.failed} TEST(S) FAILED`)
  }
  console.log("=".repeat(60))
}
