import type React from "react"
import type { Metadata } from "next"

import { Analytics } from "@vercel/analytics/next"
import { Toaster } from "sonner"
import "./globals.css"

import { Geist_Mono, Inter as V0_Font_Inter, Geist_Mono as V0_Font_Geist_Mono, Source_Serif_4 as V0_Font_Source_Serif_4 } from 'next/font/google'

// Initialize fonts
const _inter = V0_Font_Inter({ subsets: ['latin'], weight: ["100","200","300","400","500","600","700","800","900"] })
const _geistMono = V0_Font_Geist_Mono({ subsets: ['latin'], weight: ["100","200","300","400","500","600","700","800","900"] })
const _sourceSerif_4 = V0_Font_Source_Serif_4({ subsets: ['latin'], weight: ["200","300","400","500","600","700","800","900"] })

export const metadata: Metadata = {
  title: "Re-New Platform",
  description: "Plateforme de gestion des repreneurs et acquisitions d'entreprises",
  generator: "v0.app",
  metadataBase: new URL('https://app.re-new.team'),
  icons: {
    icon: [
      {
        url: "/icon-light-32x32.png",
        media: "(prefers-color-scheme: light)",
      },
      {
        url: "/icon-dark-32x32.png",
        media: "(prefers-color-scheme: dark)",
      },
      {
        url: "/icon.svg",
        type: "image/svg+xml",
      },
    ],
    apple: "/apple-icon.png",
  },
  openGraph: {
    title: 'Re-New',
    description: "Accompagnement des repreneurs dans leur projet d'acquisition",
    url: 'https://app.re-new.team',
    siteName: 'Re-New',
    locale: 'fr_FR',
    type: 'website',
    // Images are auto-generated by app/opengraph-image.tsx
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Re-New',
    description: "Accompagnement des repreneurs dans leur projet d'acquisition",
    // Images are auto-generated by app/twitter-image.tsx
  },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`font-sans antialiased`} suppressHydrationWarning>
        {children}
        <Toaster
          position="bottom-right"
          richColors
          closeButton
          expand
          visibleToasts={4}
          style={{ "--width": "520px" } as React.CSSProperties}
          toastOptions={{
            duration: 4500,
            classNames: {
              toast: "min-h-16 rounded-lg border px-5 py-4 shadow-lg backdrop-blur-sm",
              success: "border-emerald-200 bg-emerald-50 text-emerald-950 shadow-[0_18px_55px_rgba(22,163,74,0.16)]",
              error: "border-red-200 bg-red-50 text-red-950 shadow-[0_18px_55px_rgba(239,68,68,0.14)]",
              warning: "border-amber-200 bg-amber-50 text-amber-950 shadow-[0_18px_55px_rgba(217,119,6,0.14)]",
              info: "border-blue-200 bg-blue-50 text-blue-950 shadow-[0_18px_55px_rgba(59,130,246,0.14)]",
              title: "text-base font-semibold leading-6",
              description: "text-sm leading-5 opacity-90",
              icon: "mt-0.5",
              closeButton: "border bg-background text-muted-foreground shadow-sm hover:bg-muted",
            },
          }}
        />
        <Analytics />
      </body>
    </html>
  )
}
