import type React from "react"
import type { Metadata } from "next"

import { Analytics } from "@vercel/analytics/next"
import { Toaster } from "sonner"
import "./globals.css"

import { Inter } from 'next/font/google'

// Initialize Inter font with only the weights we actually use
const inter = Inter({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  display: 'swap',
  variable: '--font-inter',
})

export const metadata: Metadata = {
  title: "Re-New Platform",
  description: "Plateforme de gestion des repreneurs et acquisitions d'entreprises",
  generator: "v0.app",
  metadataBase: new URL('https://app.re-new.team'),
  icons: {
    icon: [
      {
        url: "/icon-light-32x32.png",
        media: "(prefers-color-scheme: light)",
      },
      {
        url: "/icon-dark-32x32.png",
        media: "(prefers-color-scheme: dark)",
      },
      {
        url: "/icon.svg",
        type: "image/svg+xml",
      },
    ],
    apple: "/apple-icon.png",
  },
  openGraph: {
    title: 'Re-New',
    description: "Accompagnement des repreneurs dans leur projet d'acquisition",
    url: 'https://app.re-new.team',
    siteName: 'Re-New',
    locale: 'fr_FR',
    type: 'website',
    // Images are auto-generated by app/opengraph-image.tsx
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Re-New',
    description: "Accompagnement des repreneurs dans leur projet d'acquisition",
    // Images are auto-generated by app/twitter-image.tsx
  },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning className={inter.variable}>
      <body className={`${inter.className} antialiased`} suppressHydrationWarning>
        {children}
        <Toaster
          position="bottom-right"
          toastOptions={{
            duration: 3000,
            style: {
              background: 'white',
              border: '1px solid #e5e7eb',
              padding: '12px 16px',
            },
          }}
        />
        <Analytics />
      </body>
    </html>
  )
}
