/**
 * Decision #138 / Ticket #137: explicit business-field allowlists.
 * New database columns are reviewed here rather than silently joining a download.
 */
export const FULL_EXPORT_OPPORTUNITY_COLUMNS = [
  "id",
  "reference",
  "status",
  "source_id",
  "source_label",
  "source_visibility",
  "sector",
  "activity",
  "location",
  "description",
  "revenue_meur",
  "ebitda_keur",
  "headcount",
  "date_added",
  "repreneur_visibility",
  "public_title",
  "anonymized_description",
  "staff_notes",
  "imported_from",
  "imported_at",
  "archived_at",
  "created_by",
  "created_at",
  "updated_at",
  "headcount_range",
  "repreneur_exposure",
  "teaser_summary",
  "public_description_approved_hash",
  "public_description_approved_at",
  "public_description_approved_by",
  "internal_notes",
  "source_office_id",
  "updated_by",
  "date_added_precision",
  "geography_node_id",
  "is_demo",
  "source_identity_to_verify",
  "demo_classification_created_by",
  "demo_classification_created_at",
  "demo_classification_updated_at",
  "demo_classification_updated_by",
] as const

export const FULL_EXPORT_MATCH_COLUMNS = [
  "id",
  "opportunity_id",
  "repreneur_id",
  "status",
  "platform_recommendation",
  "platform_score",
  "platform_reasons",
  "human_recommendation",
  "human_notes",
  "created_by",
  "reviewed_by",
  "reviewed_at",
  "created_at",
  "updated_at",
  "pursuit_stage",
  "pursuit_stage_notes",
  "pursuit_stage_updated_by",
  "pursuit_stage_updated_at",
  "nda_status",
  "nda_document_id",
  "nda_notes",
  "nda_updated_by",
  "nda_updated_at",
  "decline_reason_categories",
  "decline_reason_text",
  "interest_expressed_at",
  "interest_notification_sent_at",
  "nda_received_at",
  "nda_signed_at",
  "nda_waived_at",
  "nda_waived_by",
  "recommendation_published_at",
  "recommendation_expires_at",
  "recommendation_renewed_at",
  "recommendation_renewed_by",
] as const

const LEGACY_OPPORTUNITY_COLUMNS = new Set([
  "source_id",
  "source_label",
  "source_visibility",
  "repreneur_visibility",
  "anonymized_description",
  "staff_notes",
])

export const FULL_EXPORT_REPRENEUR_COLUMNS = [
  "id",
  "first_name",
  "last_name",
  "email",
  "phone",
  "lifecycle_status",
  "journey_stage",
  "is_demo",
] as const

export const FULL_EXPORT_SOURCE_COLUMNS = [
  "firm_id",
  "firm_name",
  "office_id",
  "office_name",
  "office_city",
  "office_general_email",
  "office_general_phone",
  "legacy_firm_id",
  "legacy_firm_name",
] as const

export const FULL_EXPORT_CONTACT_COLUMNS = [
  "id",
  "opportunity_id",
  "affiliation_id",
  "legacy_source_contact_id",
  "contact_name_snapshot",
  "contact_email_snapshot",
  "contact_phone_snapshot",
  "is_primary",
  "is_active",
  "linked_by",
  "linked_at",
  "removed_by",
  "removed_at",
  "contact_id",
  "current_contact_name",
  "current_contact_email",
  "current_contact_phone",
  "affiliation_office_id",
  "affiliation_job_title",
  "affiliation_is_active",
  "affiliation_started_at",
  "affiliation_ended_at",
] as const

export const FULL_EXPORT_PURSUIT_EVENT_COLUMNS = [
  "id",
  "match_id",
  "opportunity_id",
  "repreneur_id",
  "stage",
  "note",
  "created_by",
  "created_at",
] as const

export const FULL_EXPORT_LEGACY_CONTACT_COLUMNS = [
  "opportunity_id",
  "source_id",
  "contact_id",
  "is_primary",
  "created_by",
  "created_at",
  "contact_name_snapshot",
  "contact_email_snapshot",
  "contact_phone_snapshot",
  "canonical_opportunity_contact_id",
  "current_contact_name",
  "current_contact_email",
  "current_contact_phone",
  "canonical_contact_id",
  "office_affiliation_id",
] as const

export const FULL_EXPORT_COLLECTIONS = {
  workbookHistory: {
    table: "historical_pursuit_resolved_rows",
    header: "pursuit_workbook_history_json",
    scope: "match",
    time: "applied_at",
    columns: ["id", "match_id", "opportunity_id", "repreneur_id", "source_sha256", "source_sheet", "source_row",
      "source_offer_label", "source_opportunity_reference", "completed_source_stages", "not_applicable_source_stages",
      "last_reported_source_stage", "raw_drop_reason", "event_dates_unknown", "source_terminal", "resolution_blockers",
      "review_flags", "mapped_match_status", "apply_outcome", "applied_by", "applied_at",
      "clarification_outcome", "resolved_reference", "clarified_at"],
  },
  documents: {
    table: "opportunity_documents",
    header: "opportunity_documents_json",
    scope: "opportunity",
    time: "uploaded_at",
    columns: [
      "id",
      "opportunity_id",
      "title",
      "document_type",
      "visibility",
      "file_name",
      "mime_type",
      "size_bytes",
      "uploaded_by",
      "uploaded_at",
      "updated_at",
      "repreneur_approved_at",
      "repreneur_approved_by",
    ],
  },
  ndaArtifacts: {
    table: "opportunity_nda_artifacts",
    header: "pursuit_nda_artifacts_json",
    scope: "artifact",
    time: "recorded_at",
    columns: [
      "id",
      "opportunity_id",
      "match_id",
      "document_id",
      "artifact_role",
      "version_number",
      "content_sha256",
      "supersedes_artifact_id",
      "recorded_by",
      "recorded_at",
    ],
  },
  evidence: {
    table: "opportunity_pursuit_evidence",
    header: "pursuit_evidence_json",
    scope: "identity",
    time: "recorded_at",
    columns: [
      "id",
      "match_id",
      "opportunity_id",
      "repreneur_id",
      "event_type",
      "actor",
      "evidence_reference",
      "nda_artifact_id",
      "document_id",
      "metadata",
      "recorded_at",
    ],
  },
  grants: {
    table: "opportunity_pursuit_confidential_grants",
    header: "pursuit_confidential_grants_json",
    scope: "pair",
    time: "created_at",
    columns: [
      "id",
      "match_id",
      "opportunity_id",
      "information_memo_document_id",
      "source_firm_id",
      "source_firm_name",
      "source_office_id",
      "source_office_name",
      "disclosed_contacts",
      "source_disclosed_at",
      "granted_by",
      "revoked_at",
      "revoked_by",
      "revoked_reason",
      "created_at",
      "cycle_started_evidence_id",
      "gate_2_evidence_id",
      "dispatch_evidence_id",
      "nda_expires_at",
    ],
  },
  handoffs: {
    table: "opportunity_pursuit_handoff_deliveries",
    header: "pursuit_handoff_deliveries_json",
    scope: "match",
    time: "created_at",
    columns: [
      "id",
      "match_id",
      "upstream_evidence_id",
      "handoff_type",
      "ma_interaction_id",
      "delivery_status",
      "created_by",
      "last_attempted_by",
      "attempt_count",
      "attempt_started_at",
      "last_attempt_at",
      "sent_at",
      "finalized_at",
      "evidence_id",
      "attachment_snapshot",
      "created_at",
    ],
  },
  memoNotifications: {
    table: "opportunity_memo_notifications",
    header: "pursuit_memo_notifications_json",
    scope: "identity",
    time: "created_at",
    columns: [
      "id",
      "match_id",
      "opportunity_id",
      "repreneur_id",
      "recipient_email",
      "status",
      "attempt_count",
      "last_attempt_at",
      "failed_at",
      "sent_at",
      "created_at",
      "updated_at",
    ],
  },
  assignmentNotifications: {
    table: "opportunity_recommendation_assignment_notifications",
    header: "pursuit_assignment_notifications_json",
    scope: "match",
    time: "created_at",
    columns: [
      "id",
      "match_id",
      "created_by",
      "created_at",
      "recipient_email",
      "recipient_first_name",
      "public_title",
      "teaser_summary",
      "email_subject",
      "copy_version",
    ],
  },
  closures: {
    table: "opportunity_closure_history",
    header: "opportunity_closure_history_json",
    scope: "opportunity",
    time: "closed_at",
    columns: ["id", "opportunity_id", "reason", "closed_by", "closed_at"],
  },
  pauses: {
    table: "opportunity_pause_history",
    header: "opportunity_pause_history_json",
    scope: "opportunity",
    time: "paused_at",
    columns: [
      "id",
      "opportunity_id",
      "reason",
      "previous_status",
      "paused_by",
      "paused_at",
    ],
  },
  interactions: {
    table: "ma_interactions",
    header: "opportunity_interactions_json",
    scope: "opportunity",
    time: "occurred_at",
    columns: [
      "id",
      "office_id",
      "affiliation_id",
      "opportunity_id",
      "channel",
      "direction",
      "occurred_at",
      "owner_staff_user_id",
      "owner_verification_state",
      "owner_verified_by",
      "owner_verified_at",
      "title",
      "summary",
      "outcome",
      "next_action",
      "next_action_due_at",
      "template_key",
      "recipient_email_snapshot",
      "body_markdown",
      "delivery_status",
      "delivery_finalized_at",
      "sent_at",
      "created_by",
      "created_at",
      "updated_by",
      "updated_at",
    ],
  },
} as const

export const FULL_EXPORT_EVIDENCE_METADATA_COLUMNS = [
  "source_firm_name",
  "source_office_name",
  "historical_revalidation",
  "blank_nda_present_at_validation",
  "cycle_started_evidence_id",
  "dispatch_evidence_id",
  "gate_2_evidence_id",
  "e7_evidence_id",
  "handoff_delivery_id",
  "information_memo_document_id",
  "initiated_by",
  "ma_interaction_id",
  "nda_expires_at",
  "previous_validation_evidence_id",
  "renew_artifact_id",
  "renew_validation_id",
  "repreneur_artifact_id",
  "repreneur_validation_id",
  "upstream_evidence_id",
  "approval_scope",
  "memo_approved_by",
  "memo_approval_evidence_id",
  "grant_evidence_id",
  "drop_reason",
] as const

export const FULL_EXPORT_ATTACHMENT_COLUMNS = [
  "artifact_id",
  "document_id",
  "content_sha256",
  "file_name",
  "mime_type",
  "size_bytes",
] as const
export const FULL_EXPORT_DISCLOSED_CONTACT_COLUMNS = [
  "opportunity_contact_id",
  "contact_id",
  "name",
  "email",
  "phone",
] as const

export const FULL_OPPORTUNITY_EXPORT_HEADERS = [
  ...FULL_EXPORT_OPPORTUNITY_COLUMNS.map(
    (column) =>
      `opportunity_${LEGACY_OPPORTUNITY_COLUMNS.has(column) ? "legacy_" : ""}${column}`,
  ),
  ...FULL_EXPORT_MATCH_COLUMNS.map((column) => `pursuit_${column}`),
  ...FULL_EXPORT_REPRENEUR_COLUMNS.map((column) => `repreneur_${column}`),
  ...FULL_EXPORT_SOURCE_COLUMNS.map((column) => `source_${column}`),
  "opportunity_pipeline_status",
  "pursuit_namespace_status",
  "opportunity_contacts_json",
  "pursuit_stage_history_json",
  ...Object.values(FULL_EXPORT_COLLECTIONS).map(
    (collection) => collection.header,
  ),
  "opportunity_legacy_contacts_json",
]
