import { Metadata } from 'next'
import WelcomeClient from './client'

export const metadata: Metadata = {
  title: 'Rejoignez Re-New | Questionnaire Repreneur',
  description: 'Complétez votre profil repreneur et rejoignez le réseau Re-New pour votre projet d\'acquisition.',
  openGraph: {
    title: 'Rejoignez Re-New',
    description: 'Questionnaire repreneur - Démarrez votre projet d\'acquisition avec Re-New',
    url: 'https://app.re-new.team/welcome',
    // Images are auto-generated by app/welcome/opengraph-image.tsx
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Rejoignez Re-New',
    description: 'Questionnaire repreneur - Démarrez votre projet d\'acquisition',
    // Images are auto-generated by app/welcome/twitter-image.tsx
  },
}

export default function WelcomePage() {
  return <WelcomeClient />
}
