#!/usr/bin/env bash
set -euo pipefail
root="$(cd "$(dirname "$0")/.." && pwd)"; bin=/opt/homebrew/opt/postgresql@16/bin; dir="$(mktemp -d /private/tmp/renew-pdr43.XXXXXX)"; port=55449
cleanup(){ [ -f "$dir/postmaster.pid" ] && "$bin/pg_ctl" -D "$dir" -m immediate stop >/dev/null 2>&1 || true; rm -rf "$dir"; }; trap cleanup EXIT
"$bin/initdb" -D "$dir" --no-locale --auth-local=trust >/dev/null; "$bin/pg_ctl" -D "$dir" -o "-p $port" -w start >/dev/null; "$bin/createdb" -p "$port" pdr43
p=("$bin/psql" -v ON_ERROR_STOP=1 -p "$port" -d pdr43)
"${p[@]}" -c "CREATE EXTENSION pgcrypto; CREATE SCHEMA storage; CREATE TABLE storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]); CREATE ROLE anon; CREATE ROLE authenticated; CREATE ROLE service_role; CREATE TABLE public.pdr_proposals(id uuid primary key default gen_random_uuid(),requester_actor text default 'Dev team',attachments jsonb default '[]',original_text text default '',conversation jsonb default '[]',proposal_type text default '',problem_statement text default '',ai_rationale text default '',status text default '',created_by text default '',reviewer_note text default '',created_at timestamptz default now(),updated_at timestamptz default now()); CREATE TABLE public.pdr_requests(id uuid primary key default gen_random_uuid()); CREATE TABLE public.pdr_feedback(id uuid primary key default gen_random_uuid()); CREATE TABLE public.pdr_goals(id uuid primary key default gen_random_uuid()); CREATE TABLE public.pdr_milestones(id uuid primary key default gen_random_uuid()); CREATE TABLE public.pdr_work_cards(id uuid primary key default gen_random_uuid()); GRANT SELECT ON ALL TABLES IN SCHEMA public TO anon,authenticated;"
"${p[@]}" -f "$root/supabase/migrations/20260830113000_wave_pdr_staff_intake.sql"
"${p[@]}" -c "DO \$\$ BEGIN IF has_table_privilege('anon','public.pdr_proposals','SELECT') THEN RAISE EXCEPTION 'public grant remained'; END IF; IF NOT has_table_privilege('service_role','public.pdr_proposals','SELECT') THEN RAISE EXCEPTION 'service grant missing'; END IF; END \$\$; INSERT INTO public.wave_pdr_governance_capabilities(singleton,actor_user_id,granted_by) VALUES(true,'ivan','test'); DO \$\$ BEGIN BEGIN INSERT INTO public.wave_pdr_governance_capabilities(singleton,actor_user_id,granted_by) VALUES(true,'other','test'); RAISE EXCEPTION 'singleton allowed'; EXCEPTION WHEN unique_violation THEN NULL; END; BEGIN UPDATE public.pdr_work_cards SET id=id; RAISE EXCEPTION 'work card update allowed'; EXCEPTION WHEN raise_exception THEN NULL; END; END \$\$;"
# Pre-retirement rollback restores only public reads and unfreezes legacy cards;
# private metadata and singleton evidence deliberately remain.
"${p[@]}" -c "DROP TRIGGER wave_pdr_historical_work_cards_read_only ON public.pdr_work_cards; GRANT SELECT ON public.pdr_proposals TO anon,authenticated; ALTER TABLE public.pdr_proposals DROP CONSTRAINT pdr_proposals_disposition_audit_check; DO \$\$ BEGIN IF NOT has_table_privilege('anon','public.pdr_proposals','SELECT') THEN RAISE EXCEPTION 'grant rollback failed'; END IF; IF NOT EXISTS(SELECT 1 FROM public.wave_pdr_governance_capabilities WHERE singleton) THEN RAISE EXCEPTION 'capability evidence lost'; END IF; END \$\$;"
echo 'PDR #43 disposable migration and rollback rehearsal passed'
