#!/usr/bin/env bash
set -euo pipefail

# Runs only against a disposable local PostgreSQL cluster. It never reads
# project credentials or production data.
repo_root="$(cd "$(dirname "$0")/.." && pwd)"
pg_bin="$(pg_config --bindir)"
for binary in initdb pg_ctl createdb psql; do
  [ -x "$pg_bin/$binary" ] || { echo "Missing PostgreSQL binary: $pg_bin/$binary" >&2; exit 1; }
done

tmpdir="$(mktemp -d)"
port=55461
cleanup() {
  "$pg_bin/pg_ctl" -D "$tmpdir/data" -m immediate stop >/dev/null 2>&1 || true
  rm -rf "$tmpdir"
}
trap cleanup EXIT

"$pg_bin/initdb" -D "$tmpdir/data" -U renew_w161_admin --no-locale >/dev/null
"$pg_bin/pg_ctl" -D "$tmpdir/data" -o "-p $port" -w start >/dev/null
"$pg_bin/createdb" -h 127.0.0.1 -p "$port" -U renew_w161_admin w161_rehearsal
psql=("$pg_bin/psql" -X -v ON_ERROR_STOP=1 -h 127.0.0.1 -p "$port" -U renew_w161_admin -d w161_rehearsal)

"${psql[@]}" -c "CREATE ROLE postgres NOLOGIN; CREATE ROLE anon NOLOGIN; CREATE ROLE authenticated NOLOGIN; CREATE ROLE service_role NOLOGIN BYPASSRLS; CREATE SCHEMA extensions; CREATE SCHEMA auth; CREATE TABLE auth.users (id UUID PRIMARY KEY); CREATE FUNCTION auth.uid() RETURNS UUID LANGUAGE sql STABLE AS 'SELECT NULL::UUID';" >/dev/null
"${psql[@]}" --file "$repo_root/supabase/schema/771_extensions.sql" >/dev/null
# The checked-in production-shaped schema is generated by a newer PostgreSQL
# release. The one unsupported session setting is irrelevant to its DDL.
sed -e '/transaction_timeout/d' -e 's/,MAINTAIN//g' -e 's/MAINTAIN,//g' "$repo_root/supabase/schema/771_public_schema.sql" | "${psql[@]}" >/dev/null

"${psql[@]}" <<'SQL' >/dev/null
INSERT INTO public.repreneurs (id, first_name, last_name, email) VALUES
  ('00000000-0000-4000-8000-000000000161', 'Existing', 'Profile', 'existing-w161@example.test');
CREATE TABLE public.w161_before_repreneurs AS
  SELECT id, row_to_json(repreneurs)::jsonb - 'updated_at' AS profile
  FROM public.repreneurs;
SQL

"${psql[@]}" --file "$repo_root/supabase/migrations/20260829130000_w161_repreneur_target_ebitda_range.sql" >/dev/null

"${psql[@]}" <<'SQL'
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'repreneurs'
      AND column_name IN ('target_ebitda_min_keur', 'target_ebitda_max_keur')
    GROUP BY table_name HAVING count(*) = 2
  ) THEN RAISE EXCEPTION 'W-161 columns missing'; END IF;
  IF EXISTS (
    SELECT 1 FROM public.repreneurs r JOIN public.w161_before_repreneurs b USING (id)
    WHERE (row_to_json(r)::jsonb - 'updated_at' - 'target_ebitda_min_keur' - 'target_ebitda_max_keur') IS DISTINCT FROM b.profile
       OR r.target_ebitda_min_keur IS NOT NULL OR r.target_ebitda_max_keur IS NOT NULL
  ) THEN RAISE EXCEPTION 'existing repreneur changed outside additive null columns'; END IF;
END $$;

UPDATE public.repreneurs
SET target_ebitda_min_keur = 125.50, target_ebitda_max_keur = 900.00
WHERE id = '00000000-0000-4000-8000-000000000161';

DO $$
BEGIN
  IF (SELECT target_ebitda_min_keur || ':' || target_ebitda_max_keur FROM public.repreneurs WHERE id = '00000000-0000-4000-8000-000000000161') <> '125.50:900.00' THEN
    RAISE EXCEPTION 'W-161 round trip failed';
  END IF;
END $$;

UPDATE public.repreneurs SET target_ebitda_min_keur = NULL, target_ebitda_max_keur = 500 WHERE id = '00000000-0000-4000-8000-000000000161';
UPDATE public.repreneurs SET target_ebitda_min_keur = 500, target_ebitda_max_keur = NULL WHERE id = '00000000-0000-4000-8000-000000000161';
SQL

if "${psql[@]}" -c "UPDATE public.repreneurs SET target_ebitda_min_keur = -1 WHERE id = '00000000-0000-4000-8000-000000000161';" >/dev/null 2>&1; then
  echo "negative EBITDA bound unexpectedly accepted" >&2; exit 1
fi
if "${psql[@]}" -c "UPDATE public.repreneurs SET target_ebitda_min_keur = 700, target_ebitda_max_keur = 600 WHERE id = '00000000-0000-4000-8000-000000000161';" >/dev/null 2>&1; then
  echo "reversed EBITDA range unexpectedly accepted" >&2; exit 1
fi

"${psql[@]}" -c "DROP TABLE public.w161_before_repreneurs" >/dev/null

echo "W-161 disposable migration rehearsal passed"
