#!/usr/bin/env bash
set -euo pipefail
root="$(cd "$(dirname "$0")/.." && pwd)"; bin=/opt/homebrew/opt/postgresql@16/bin; dir="$(mktemp -d /private/tmp/renew-pdr43.XXXXXX)"; port=55449
cleanup(){ [ -f "$dir/postmaster.pid" ] && "$bin/pg_ctl" -D "$dir" -m immediate stop >/dev/null 2>&1 || true; rm -rf "$dir"; }; trap cleanup EXIT
"$bin/initdb" -D "$dir" --no-locale --auth-local=trust >/dev/null; "$bin/pg_ctl" -D "$dir" -o "-p $port" -w start >/dev/null; "$bin/createdb" -p "$port" pdr43
p=("$bin/psql" -v ON_ERROR_STOP=1 -p "$port" -d pdr43)
"${p[@]}" -c "CREATE EXTENSION pgcrypto; CREATE SCHEMA storage; CREATE TABLE storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]); INSERT INTO storage.buckets VALUES('pdr-attachments','pdr-attachments',true,20971520,NULL); CREATE ROLE anon; CREATE ROLE authenticated; CREATE ROLE service_role; CREATE TABLE public.pdr_proposals(id uuid primary key default gen_random_uuid(),requester_actor text default 'Dev team',attachments jsonb default '[]',original_text text default '',conversation jsonb default '[]',proposal_type text default '',problem_statement text default '',ai_rationale text default '',status text default '',created_by text default '',reviewer_note text default '',created_at timestamptz default now(),updated_at timestamptz default now()); CREATE TABLE public.pdr_requests(id uuid primary key default gen_random_uuid()); CREATE TABLE public.pdr_feedback(id uuid primary key default gen_random_uuid()); CREATE TABLE public.pdr_goals(id uuid primary key default gen_random_uuid()); CREATE TABLE public.pdr_milestones(id uuid primary key default gen_random_uuid()); CREATE TABLE public.pdr_work_cards(id uuid primary key default gen_random_uuid()); GRANT SELECT ON ALL TABLES IN SCHEMA public TO anon,authenticated;"
"${p[@]}" -f "$root/supabase/migrations/20260830113000_wave_pdr_staff_intake_foundation.sql"
"${p[@]}" -f "$root/supabase/migrations/20260830113000_wave_pdr_staff_intake_foundation.sql"
"${p[@]}" -c "INSERT INTO public.wave_pdr_governance_capabilities(singleton,actor_user_id,granted_by) VALUES(true,'ivan','test'); DO \$\$ BEGIN BEGIN INSERT INTO public.wave_pdr_governance_capabilities(singleton,actor_user_id,granted_by) VALUES(true,'other','test'); RAISE EXCEPTION 'singleton allowed'; EXCEPTION WHEN unique_violation THEN NULL; END; END \$\$;"
"${p[@]}" -c "WITH p AS (INSERT INTO public.pdr_proposals(attachments) VALUES ('[{\"url\":\"https://example.invalid/a\",\"name\":\"a.pdf\"}]') RETURNING id) INSERT INTO public.wave_pdr_request_attachments(proposal_id,storage_path,original_filename,content_type,size_bytes,uploaded_by_user_id,legacy_source_fingerprint) SELECT id,'x/a.pdf','a.pdf','application/pdf',1,'cutover',encode(digest(id::text || ':https://example.invalid/a','sha256'),'hex') FROM p;"
"${p[@]}" -f "$root/supabase/migrations/20260830113100_wave_pdr_final_retirement.sql"
"${p[@]}" -f "$root/supabase/migrations/20260830113100_wave_pdr_final_retirement.sql"
"${p[@]}" -c "DO \$\$ DECLARE legacy_table text; legacy_role text; BEGIN FOREACH legacy_table IN ARRAY ARRAY['pdr_feedback','pdr_goals','pdr_milestones','pdr_proposals','pdr_requests','pdr_work_cards'] LOOP FOREACH legacy_role IN ARRAY ARRAY['anon','authenticated'] LOOP IF has_table_privilege(legacy_role,'public.' || legacy_table,'SELECT') THEN RAISE EXCEPTION 'legacy grant remained'; END IF; END LOOP; IF NOT has_table_privilege('service_role','public.' || legacy_table,'SELECT') THEN RAISE EXCEPTION 'service grant missing'; END IF; END LOOP; IF (SELECT public FROM storage.buckets WHERE id='pdr-attachments') THEN RAISE EXCEPTION 'bucket remained public'; END IF; BEGIN INSERT INTO public.pdr_work_cards DEFAULT VALUES; RAISE EXCEPTION 'insert allowed'; EXCEPTION WHEN raise_exception THEN IF SQLERRM='insert allowed' THEN RAISE; END IF; END; BEGIN UPDATE public.pdr_work_cards SET id=id; RAISE EXCEPTION 'update allowed'; EXCEPTION WHEN raise_exception THEN IF SQLERRM='update allowed' THEN RAISE; END IF; END; BEGIN DELETE FROM public.pdr_work_cards; RAISE EXCEPTION 'delete allowed'; EXCEPTION WHEN raise_exception THEN IF SQLERRM='delete allowed' THEN RAISE; END IF; END; BEGIN TRUNCATE public.pdr_work_cards; RAISE EXCEPTION 'truncate allowed'; EXCEPTION WHEN raise_exception THEN IF SQLERRM='truncate allowed' THEN RAISE; END IF; END; END \$\$;"
# Exact final-retirement rollback restores only legacy grants, old-bucket visibility and card mutability.
# Foundation private metadata, objects and singleton evidence deliberately remain.
"${p[@]}" -f "$root/scripts/rollback-pdr-final-retirement.sql"
"${p[@]}" -c "DO \$\$ DECLARE legacy_table text; legacy_role text; BEGIN FOREACH legacy_table IN ARRAY ARRAY['pdr_feedback','pdr_goals','pdr_milestones','pdr_proposals','pdr_requests','pdr_work_cards'] LOOP FOREACH legacy_role IN ARRAY ARRAY['anon','authenticated'] LOOP IF NOT has_table_privilege(legacy_role,'public.' || legacy_table,'SELECT') THEN RAISE EXCEPTION 'rollback grant missing'; END IF; END LOOP; END LOOP; IF NOT (SELECT public FROM storage.buckets WHERE id='pdr-attachments') OR EXISTS(SELECT 1 FROM pg_trigger WHERE tgname='wave_pdr_historical_work_cards_read_only') THEN RAISE EXCEPTION 'rollback failed'; END IF; IF NOT EXISTS(SELECT 1 FROM public.wave_pdr_governance_capabilities WHERE singleton) OR NOT EXISTS(SELECT 1 FROM public.wave_pdr_request_attachments) THEN RAISE EXCEPTION 'private evidence lost'; END IF; END \$\$;"
echo 'PDR #43 disposable migration and rollback rehearsal passed'
